# configurazione del server
spring:
  profiles:
    active: test
    #active: sqlite
    #active: postgres

# configurazione del server
server:
  port: 8090
  servlet:
    contextPath: /esercitazioneJpa